log_dir: "./AuxiliaryASR-main/model_dir_humberto/"
save_freq: 1
device: "cuda"
epochs: 80
batch_size: 128
pretrained_model: "./AuxiliaryASR-main/model_dir_humberto/epoch_00200.pth"
train_data: "sippulse_correcoes_train.txt"
val_data: "sippulse_correcoes_val.txt"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 178 # IMPORTANTE! ISSO DEVE BATER COM TOKENS PLBERT/ML-PLBERT
   token_embedding_dim: 256

optimizer_params:
  lr: 0.0005
