log_dir: "./PitchExtractor-main/model_dir_base/"
save_freq: 1
device: "cuda"
epochs: 100
batch_size: 256
pretrained_model: ""
train_data: "sippulse_base_train.txt"
val_data: "sippulse_base_val.txt"
num_workers: 8
  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1